version: "3.7"

services:
  postgres_database:
    image: library/postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /Server/Postgres/Database
    volumes:
      - ${SERVER_HOME}/Server/Postgres/Database:/Server/Postgres/Database



