version: "3.7"

services:
  postfix_service:
    build: .
    container_name: postfix_service
    hostname: postfix.{{SERVER.DOMAIN}}
    restart: always
    ports:
      - 465:465
      - 587:587
    networks:
      - postmaster_network
    volumes:
      - {{SERVER.CERTIFICATION.CERTIFICATES}}:/certificates
      - {{SERVER.SERVER_HOME}}/Server/Postfix/Data:/var/lib/postfix
      - {{SERVER.SERVER_HOME}}/Server/Postfix/Queue:/var/spool/postfix
      - {{SERVER.SERVER_HOME}}/Server/Postfix/VMail:/usr/local/vmail
      - {{SERVER.SERVER_HOME}}/Server/Postfix/Mail:/var/spool/mail
      - {{SERVER.SERVER_HOME}}/Server/Postfix/Log:/var/log/postfix

networks:
  postmaster_network:
    external: true
