version: "3.7"

services:
  postgres_database:
    image: library/postgres:12
    container_name: postgres_database
    hostname: postgres.{{SERVER.DOMAIN}}
    restart: always
    ports:
    - {{DB.DB_PORT}}:5432
    environment:
      POSTGRES_USER: {{DB.DB_USER}}
      POSTGRES_PASSWORD: {{DB.DB_PASSWORD}}
      PGDATA: /Server/Postgres/Database
    volumes:
      - {{SERVER.SERVER_HOME}}/Server/Postgres/Database:/Server/Postgres/Database



