version: "3.7"

services:
  {{SERVICE.DATABASE.NAME}}:
    image: library/postgres:12
    container_name: {{SERVICE.DATABASE.NAME}}
    hostname: database.{{SERVER.DOMAIN}}
    restart: always
    ports:
      - {{DB.PORT_EXPOSED}}:{{DB.PORT}}
    networks:
      - postmaster_network
    environment:
      POSTGRES_USER: {{DB.DB_USER}}
      POSTGRES_PASSWORD: {{DB.DB_PASSWORD}}
      PGDATA: /Server/Postgres/Database
    volumes:
      - {{SERVER.SERVER_HOME}}/Server/Postgres/Database:/Server/Postgres/Database

networks:
  postmaster_network:
    external: true



