version: "3.7"

services:
  dovecot_service:
    build: .
    container_name: dovecot_service
    hostname: dovecot.{{SERVER.DOMAIN}}
    restart: always
    ports:
      - {{SERVER.DOVECOT.PORTS.IMAPS}}:993
    networks:
      - postmaster_network
    volumes:
      - {{SERVER.CERTIFICATION.CERTIFICATES}}:/certificates
      - {{SERVER.SERVER_HOME}}/Server/Dovecot/Maildir:/maildir
      - {{SERVER.SERVER_HOME}}/Server/Dovecot/VMail:/usr/local/vmail
      - {{SERVER.SERVER_HOME}}/Server/Dovecot/Masters:/etc/dovecot/masters
      - {{SERVER.SERVER_HOME}}/Server/Dovecot/Log:/var/log/dovecot

networks:
  postmaster_network:
    external: true
